#! /usr/bin/env bash
set -e

# dependencies

apt-get update
apt-get install -y curl ca-certificates
curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >> /etc/apt/sources.list

apt-get update
apt-get install -y rsync psmisc curl git libpq-dev libsqlite3-dev libsasl2-dev postgresql-9.6 postgresql-contrib-9.6 sudo vim zlib1g-dev supervisor \
	jq netcat # Parsing stellar-core JSON for standalone network and checking core HTTP server
apt-get clean

echo "\nDone installing dependencies...\n"
