#! /usr/bin/env bash
set -e

# stellar-core
apt install  libc++1 libc++abi1
#wget -O stellar-core.deb https://s3.amazonaws.com/stellar.org/releases/stellar-core/stellar-core-${STELLAR_CORE_VERSION}_amd64.deb
wget -O stellar-core.deb https://github.com/danielnapierski/stellar-core-alt/releases/download/v0.1-onfo/stellar-core-onfo_0.1-1_amd64.deb
dpkg -i stellar-core.deb
rm stellar-core.deb

ln -s /usr/bin/stellar-core /usr/local/bin/

# horizon
wget -O horizon.tar.gz https://github.com/danielnapierski/go-alt/releases/download/horizon-v${HORIZON_VERSION}/horizon-v${HORIZON_VERSION}-linux-amd64.tar.gz
tar -zxvf horizon.tar.gz
mv /horizon-v${HORIZON_VERSION}-linux-amd64/horizon /usr/local/bin
chmod +x /usr/local/bin/horizon
rm -rf horizon.tar.gz /horizon-v${HORIZON_VERSION}-linux-amd64

# friendbot
wget -O friendbot.tar.gz https://github.com/danielnapierski/go-alt/releases/download/horizon-v0.15-onfo-dev/friendbot.tar.gz
tar -zxvf friendbot.tar.gz
mv friendbot /usr/local/bin/
mkdir -p /opt/stellar/friendbot/etc
mv friendbot.cfg /opt/stellar/friendbot/etc

echo "\nDone installing stellar-core, friendbot and horizon...\n"
