---
- name: install and start onfo
  hosts: observer_nodes
  become: true

  vars:
# These are not used, yet:
    private_key: OnfoDevOpsKeyPair.pem
    user_name: ec2-user

  tasks:
  - name: 'yum upgrade all packages'
    yum:
      name: '*'
      state: latest

  - name: yum install docker
    yum: name=docker state=latest

  - name: start docker
    service: name=docker state=started

  - name: pip install docker-py
    pip:
      name: docker-py

  - name: pull onfo image from dockerhub
    docker_image:
      name: onfo/onfo-stellar-horizon

# copy a correct config to this machine
# make a new docker image using the custom config

  - name: Restart a Onfo container
    docker_container:
      name: OnfoObserver
      image: onfo/onfo-stellar-horizon
      command: --standalone
      state: started
      restart: yes
#    devices:
#     - "/dev/sda:/dev/xvda:rwm"
      ports:
        - "8000:8000"
        - "11625:11625"
        - "11626:11626"

# $ ansible-playbook -i hosts.ini --private-key=/Users/danielnapierski/github/onfo/OnfoDevOpsKeyPair.pem -u ec2-user observer.yaml

# ssh -i "OnfoDevOpsKeyPair.pem" ec2-user@ec2-18-191-175-166.us-east-2.compute.amazonaws.com
# ssh -i private_key username@[hosts]
# ansible masters -m shell -a "pwd" --private-key=/home/ec2-user/openshift-aws-installer-image/ck_workshop.pem -u ec2-user
#ansible observer_nodes -m shell -a "pwd" -i hosts.ini --private-key=/Users/danielnapierski/github/onfo/OnfoDevOpsKeyPair.pem -u ec2-user
